name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: nevermined-io/nvm-tools-actions@v0.12.0
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          contracts-version: 'v3.2.1'
          node: 'false'
          marketplace: 'false'

      - name: Install dependencies
        run: yarn

      - name: Check formatting and linting
        run: |
          yarn format
          yarn lint

      - name: Test build
        run: yarn build

      - name: unit-tests
        env:
          SEED_WORDS: ${{ secrets.TEST_MNEMONIC }}
        run: |
          nvm-tools copy-artifacts ./artifacts
          yarn test